# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uts', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=256, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uts', models.DateTimeField(auto_now_add=True)),
                ('page', models.PositiveIntegerField(db_index=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dt.Record')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='record',
            index_together=set([('active', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='recordpage',
            unique_together=set([('record', 'page')]),
        ),
        migrations.AlterIndexTogether(
            name='recordpage',
            index_together=set([('record', 'page')]),
        ),
    ]
